//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sidebar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sidebar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auros.WebUI.Resources.Admin.Sidebar.Sidebar", typeof(Sidebar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Ana_Səhifə {
            get {
                return ResourceManager.GetString("Ana Səhifə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string Bitmə_Tarixi {
            get {
                return ResourceManager.GetString("Bitmə Tarixi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Bizimlə_Əlaqə {
            get {
                return ResourceManager.GetString("Bizimlə Əlaqə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brends.
        /// </summary>
        public static string Brendlər {
            get {
                return ResourceManager.GetString("Brendlər", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnsert.
        /// </summary>
        public static string Daxil_et {
            get {
                return ResourceManager.GetString("Daxil et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        public static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Düzəliş_et {
            get {
                return ResourceManager.GetString("Düzəliş et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun.
        /// </summary>
        public static string Əyləncə {
            get {
                return ResourceManager.GetString("Əyləncə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Hesab_Parametrləri {
            get {
                return ResourceManager.GetString("Hesab Parametrləri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Hesabdan_çıxış {
            get {
                return ResourceManager.GetString("Hesabdan çıxış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to Sign Out.
        /// </summary>
        public static string Hesabdan_Çıxmaq_istəyirsiniz {
            get {
                return ResourceManager.GetString("Hesabdan Çıxmaq istəyirsiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazines.
        /// </summary>
        public static string Jurnallar {
            get {
                return ResourceManager.GetString("Jurnallar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string Kart_Nömrəsi {
            get {
                return ResourceManager.GetString("Kart Nömrəsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Not Found.
        /// </summary>
        public static string Kart_Tapılmadı {
            get {
                return ResourceManager.GetString("Kart Tapılmadı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        public static string Mebel {
            get {
                return ResourceManager.GetString("Mebel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Tools.
        /// </summary>
        public static string Web_Parametrləri {
            get {
                return ResourceManager.GetString("Web Parametrləri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Xəbərlər {
            get {
                return ResourceManager.GetString("Xəbərlər", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Yardım {
            get {
                return ResourceManager.GetString("Yardım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Yeniləmə_tarixi {
            get {
                return ResourceManager.GetString("Yeniləmə tarixi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new one.
        /// </summary>
        public static string Yenisini_əlavə_et {
            get {
                return ResourceManager.GetString("Yenisini əlavə et", resourceCulture);
            }
        }
    }
}